# Tone of Voice Guide

## Overall Tone
- Friendly and approachable
- Authoritative but not condescending
- Clear and concise
- Engaging and conversational
- Educational without being overly academic

## Content Style
- Use active voice where possible
- Write in second person ("you") to directly address the reader
- Maintain a balanced perspective, acknowledging different viewpoints
- Include rhetorical questions occasionally to engage the reader
- Use metaphors and analogies to explain complex concepts
- Keep paragraphs relatively short (3-5 sentences)
- Vary sentence length to create rhythm

## Language Guidelines
- Avoid jargon unless necessary (and explain when used)
- Use contractions to maintain conversational tone
- Limit adverbs, focus on strong verbs
- Include personal anecdotes sparingly to add human element
- Be specific rather than general
- Use inclusive language

## Section-Specific Tone
- Introduction: Inviting and captivating
- Main body: Informative and well-structured
- Conclusion: Reflective and forward-looking
- Call-to-action: Clear, direct, and motivating

## Prohibited Elements
- Aggressive sales language
- Politically charged statements
- Overly dramatic claims
- Excessive exclamation points
- Click-bait style headings